### ISSUE TITLE
1.2.0 supports only log4j2

### ISSUE THREAD

**Issue by robertoschwald** [tobias-/slack-appender#2]
It seems 1.2.0 switched to log4j2.
This may be reflected in the README, and maybe add a reference to the last log4j supported version.

**Comment by tobias-** [comment]
Uhm.. yes, well, I really didn't think anyone actually used this, so I haven't even bothered to add any Changelog.

I've made some documentation. Please review it and comment on it. I'll put it into master directly, so comment in this issue.

To answer your question, latest with 1.x is 0.99.7, so at least I did a proper major version change even though I completely forgot about the documentation.

**Comment by robertoschwald** [comment]
Great! Worked me through the versions yesterday and figured that out. 0.99.7 works with 1.x here in a Grails 2.x project (log4j 1.x). Thanks for the changes.
